name = "nostr-shrine"
main = "src/worker.ts"
compatibility_date = "2025-09-02"
workers_dev = true
logpush = true

[vars]
# SHRINE_PUBKEY_HEX = ""
# SHRINE_PRIVKEY_HEX = ""
# ALLOWED_KINDS = "1,30023"

[[kv_namespaces]]
binding = "RATE_KV"
id = "d8f0dc9a6b544216802d1b31d37ebd1a"
